version: '3.9'
    
# Services
services:

  # Nginx Service
  nginx:
    build: ./.docker/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/var/www/wordpress
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
      - ./.docker/nginx/certs:/etc/nginx/certs
      - ./.scripts:/.scripts
      - ./.docker/nginx/logs:/var/log/nginx/
    depends_on:
      phpmyadmin:
        condition: service_healthy
      dev:
        condition: service_healthy

  # DEV Service
  dev:
    build: ./.docker/dev
    working_dir: /var/www
    user: vscode
    ports:
      - 9000:9000
      - 9003:9003
    volumes:
      - ./public:/var/www/wordpress:cached
      - ./.scripts:/.scripts
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.devcontainer/.ssh:/home/vscode/.ssh
      - ./vendor:/home/vscode/.composer/vendor
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: php -v
      interval: 5s
      retries: 10

  # MySQL Service
  db:
    image: mariadb:10.5.8
    hostname: db.local
    ports:
      - 9006:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db/files:/import-files
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    environment:
      PMA_HOST: db
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: php -v
      interval: 5s
      retries: 10

  # DNS Service
  dns:
    build: ./.docker/dns
    restart: always
    volumes:
      - ./.docker/dns/config:/etc/dnsmasq.d
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN

# Volumes
volumes:
  mysqldata: null
  phpmyadmindata: null
  