version: '3.9'
    
# Services
services:

  # Nginx Service
  nginx:
    build: ./.docker/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/gravity
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
      - ./.docker/nginx/certs:/etc/nginx/certs
      - ./.scripts:/.scripts
      - ./.docker/nginx/logs:/var/log/nginx/
    depends_on:
      phpmyadmin:
        condition: service_healthy
      php:
        condition: service_healthy

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/gravity
      - ./.scripts:/.scripts
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: php -v
      interval: 5s
      retries: 10

  # MySQL Service
  db:
    image: mariadb:10.5.8
    hostname: db.loc
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gravity
    volumes:
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db/files:/import-files
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: php -v
      interval: 5s
      retries: 10

  # DNS Service
  dns:
    build: ./.docker/dns
    restart: always
    volumes:
      - ./.docker/dns/config:/etc/dnsmasq.d
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN

# Volumes
volumes:
  mysqldata: null
  phpmyadmindata: null
  